#!/bin/sh

# update from git
echo "Updating ~/UTR5..."
cd ~/UTR5 # just to make sure
git pull

# install packages
echo "Updating packages"
sudo apt-get install python-smbus i2c-tools python-picamera python-opencv
#sudo pip install opencv-python

# update button listeners
echo "Updating button listeners"
sudo rm /etc/init.d/UTR5*
# sudo crontab -e
#   then append:
# @reboot /usr/bin/python /home/pi/bin/start
# @reboot /usr/bin/python /home/pi/bin/stop

# update needed libraries: RTIMULib2
installed=`python -c 'import pkgutil; print(1 if pkgutil.find_loader("RTIMU") else 0)'`
if [ "$installed" -eq 0 ];then
	echo "Missing RTIMULib2, installing...";
	sudo apt-get install python-dev
	mkdir ~/UTR5/bin/temp
	cd ~/UTR5/bin/temp
	git clone https://github.com/RTIMULib/RTIMULib2.git
	cd RTIMULib2/Linux/python
	python setup.py build
	sudo python setup.py install
	cd ~/UTR5
	rm -rf bin/temp
fi

echo "Update complete!"
